@startuml Stockmanagement_C4ComponentBackend
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml
!include FONTAWESOME/server.puml
!include DEVICONS/database.puml
!include FONTAWESOME/server.puml
!include DEVICONS/bootstrap.puml
!include DEVICONS/wordpress.puml

title Stockmanagement C4Component-Diagram

Container(ordermanagement, "Ordermanagement", "Hauptmodul", "Verwaltet die Logik im Bezug auf die Bestellungen")
Container(sharedkernel, "Sharedkernel", "DDD-Modul", "Stellt Funktionen für die Hauptmodule bereit")
ContainerDb(database, "Datenbank", "H2", "Speichert die Inhalte der Applikation sowie die Informationen der Kunden, Bestellungen und der Lagerware", "database")

Container_Boundary(stockmanagement, "Stockmanagement") {
    
    Component(adapter, "Adapter", "Kommunikation", "Verwaltet die Kommunikation zwischen dem System und externen Schnittstellen durch HTTP und Nachrichtenverarbeitung.")
    Component(business, "Business", "Geschäftsmodelle & Logik", "Enthält Geschäftsmodelle und Logik für Verpackung und Lieferung.")
    Component(db, "DB", "Datenzugriffs-Interfaces", "Stellt Datenzugriffs-Interfaces für Verpackungs- und Verpackungsartikel bereit.")
    
    ordermanagement ..> adapter : sends Events
    adapter ..> ordermanagement : sends Events
    Rel(business, adapter, "provides functions")
    Rel(db, adapter, "provides functions")
    Rel(sharedkernel, adapter, "provides functions")
    Rel(business, db, "provides functions")

    Rel(db, database, "JPA", "Speichert und liest Daten aus/auf Datenbank")
}

@enduml
